# This file was generated by GoReleaser. DO NOT EDIT.
cask "twig" do
  version "0.2.8"

  on_macos do
    on_intel do
      sha256 "22347621856f167d1b57b0913a428b1ab37bee9449375f60ab64e4816186631d"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "23dc251643f381a96ee8ee7f9bb17503375aa93a77cb354ab00b0db38a0f6722"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "21016c14e88a44f7daf1e1c9e5580688f121577335327771caa7f1a403b0ac02"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "29c1f3f9c4278cd900556e524e84ea3b21134371155b71609705ff38c4aa2dad"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_linux_arm64.tar.gz"
    end
  end

  name "twig"
  desc "Git worktrees, one short command away"
  homepage "https://joshpadnick.com/twig/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/twig"]
    end
  end

  # No zap stanza required

end
