# This file was generated by GoReleaser. DO NOT EDIT.
cask "twig" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0fd735981cc30dfeabaad120c4e2bfe076c85044a13ca784a3b36042a1cf5fb3"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4bbbe559ffb3fc189f443359dcc6eca0eeec2ad39f526bf0422ca247f9774c2f"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "d53d88b6e301de5c29d4ebf96bd8ba0fea2f23409b5df7fbb8e44adff328e739"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "8573da3b244834a2d046451a527bdaccafbe332a819839212547c376d2851c86"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_linux_arm64.tar.gz"
    end
  end

  name "twig"
  desc "Git worktrees, one short command away"
  homepage "https://joshpadnick.com/twig/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/twig"]
    end
  end

  # No zap stanza required

end
