# This file was generated by GoReleaser. DO NOT EDIT.
cask "twig" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "462a05bacedb217f427a5f618ca14064a3c762a192c85137ed1ee1c9f14adc54"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "55aa6ddbdf495603a83172ac96ec58791d584c894fe4ba8e365d8ef047b26de1"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3e563bef8b86ebd5de8b90f08113b9f6fc0511c95dc3e8d4d1e686334f6c788d"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d29337d31574df0e6e4b68f59133c821fbbe814d97911f41c20545ad18a1a509"
      url "https://github.com/josh-padnick/twig/releases/download/v#{version}/twig_#{version}_linux_arm64.tar.gz"
    end
  end

  name "twig"
  desc "Git worktrees, one short command away"
  homepage "https://joshpadnick.com/twig/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "twig"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/twig"]
    end
  end

  # No zap stanza required

end
